/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChatbotRouteImport } from './routes/chatbot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TicketsTicketIdRouteImport } from './routes/tickets.$ticketId'
import { Route as TechnicianTicketsRouteImport } from './routes/technician.tickets'
import { Route as TechnicianDashboardRouteImport } from './routes/technician.dashboard'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTicketsRouteImport } from './routes/admin.tickets'
import { Route as AdminTicketsTicketIdRouteImport } from './routes/admin.tickets.$ticketId'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatbotRoute = ChatbotRouteImport.update({
  id: '/chatbot',
  path: '/chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsTicketIdRoute = TicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => TicketsRoute,
} as any)
const TechnicianTicketsRoute = TechnicianTicketsRouteImport.update({
  id: '/technician/tickets',
  path: '/technician/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnicianDashboardRoute = TechnicianDashboardRouteImport.update({
  id: '/technician/dashboard',
  path: '/technician/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/admin/tickets',
  path: '/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTicketsTicketIdRoute = AdminTicketsTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AdminTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/tickets': typeof TechnicianTicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/tickets': typeof TechnicianTicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatbot': typeof ChatbotRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/admin/tickets': typeof AdminTicketsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/technician/dashboard': typeof TechnicianDashboardRoute
  '/technician/tickets': typeof TechnicianTicketsRoute
  '/tickets/$ticketId': typeof TicketsTicketIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/tickets/$ticketId': typeof AdminTicketsTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/tickets'
    | '/admin/tickets'
    | '/admin/users'
    | '/technician/dashboard'
    | '/technician/tickets'
    | '/tickets/$ticketId'
    | '/admin/'
    | '/admin/tickets/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/tickets'
    | '/admin/tickets'
    | '/admin/users'
    | '/technician/dashboard'
    | '/technician/tickets'
    | '/tickets/$ticketId'
    | '/admin'
    | '/admin/tickets/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/chatbot'
    | '/dashboard'
    | '/login'
    | '/settings'
    | '/signup'
    | '/tickets'
    | '/admin/tickets'
    | '/admin/users'
    | '/technician/dashboard'
    | '/technician/tickets'
    | '/tickets/$ticketId'
    | '/admin/'
    | '/admin/tickets/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatbotRoute: typeof ChatbotRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  AdminTicketsRoute: typeof AdminTicketsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  TechnicianDashboardRoute: typeof TechnicianDashboardRoute
  TechnicianTicketsRoute: typeof TechnicianTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatbot': {
      id: '/chatbot'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets/$ticketId': {
      id: '/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/tickets/$ticketId'
      preLoaderRoute: typeof TicketsTicketIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/technician/tickets': {
      id: '/technician/tickets'
      path: '/technician/tickets'
      fullPath: '/technician/tickets'
      preLoaderRoute: typeof TechnicianTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technician/dashboard': {
      id: '/technician/dashboard'
      path: '/technician/dashboard'
      fullPath: '/technician/dashboard'
      preLoaderRoute: typeof TechnicianDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/admin/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tickets/$ticketId': {
      id: '/admin/tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/admin/tickets/$ticketId'
      preLoaderRoute: typeof AdminTicketsTicketIdRouteImport
      parentRoute: typeof AdminTicketsRoute
    }
  }
}

interface TicketsRouteChildren {
  TicketsTicketIdRoute: typeof TicketsTicketIdRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsTicketIdRoute: TicketsTicketIdRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface AdminTicketsRouteChildren {
  AdminTicketsTicketIdRoute: typeof AdminTicketsTicketIdRoute
}

const AdminTicketsRouteChildren: AdminTicketsRouteChildren = {
  AdminTicketsTicketIdRoute: AdminTicketsTicketIdRoute,
}

const AdminTicketsRouteWithChildren = AdminTicketsRoute._addFileChildren(
  AdminTicketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatbotRoute: ChatbotRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TicketsRoute: TicketsRouteWithChildren,
  AdminTicketsRoute: AdminTicketsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  TechnicianDashboardRoute: TechnicianDashboardRoute,
  TechnicianTicketsRoute: TechnicianTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
